config/routes.rb
BlogTutorial::Application.routes.draw do
  

  get "sessions/home"

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    get    'logout' => :destroy
    delete 'logout' => :destroy
  end

  resources :users

  resources :posts do
    resources :comments
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>BlogTutorial</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to 'Blog on Rails', posts_path, :class => "brand" %>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><%= link_to 'Users', users_path %></li>
              <li><% unless logged_in %><%= link_to 'Log In', login_url %><% end %></li>
              <li><% if logged_in %><%= link_to 'Log Out', logout_url %><% end %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1><%= link_to blog_title, posts_path %></h1>
        <p><%= blog_description %></p>
      </div>

      <!-- Put content here -->
      <div class="row">
        <div class="span8"><!-- main content -->

          <%= yield %>

        </div>
        <div class="span4"><!-- sidebar -->
          <p>Put some sidebar content here later</p>
        </div>
      
      </div>

      <hr>

      <footer>
        <p>&copy; Chronus</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/bootstrapjs/jquery.js"></script>
    <script src="/bootstrapjs/bootstrap-transition.js"></script>
    <script src="/bootstrapjs/bootstrap-alert.js"></script>
    <script src="/bootstrapjs/bootstrap-modal.js"></script>
    <script src="/bootstrapjs/bootstrap-dropdown.js"></script>
    <script src="/bootstrapjs/bootstrap-scrollspy.js"></script>
    <script src="/bootstrapjs/bootstrap-tab.js"></script>
    <script src="/bootstrapjs/bootstrap-tooltip.js"></script>
    <script src="/bootstrapjs/bootstrap-popover.js"></script>
    <script src="/bootstrapjs/bootstrap-button.js"></script>
    <script src="/bootstrapjs/bootstrap-collapse.js"></script>
    <script src="/bootstrapjs/bootstrap-carousel.js"></script>
    <script src="/bootstrapjs/bootstrap-typeahead.js"></script>

</body>
</html>